# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-10 16:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addrecipe',
            name='username',
        ),
        migrations.AddField(
            model_name='addrecipe',
            name='username_insert',
            field=models.EmailField(default=datetime.datetime(2017, 4, 10, 16, 0, 53, 592158, tzinfo=utc), max_length=254),
            preserve_default=False,
        ),
    ]
