# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-10 16:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170410_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addrecipe',
            name='username_insert',
        ),
        migrations.AddField(
            model_name='addrecipe',
            name='username',
            field=models.CharField(default=datetime.datetime(2017, 4, 10, 16, 2, 25, 210256, tzinfo=utc), max_length=220),
            preserve_default=False,
        ),
    ]
