# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-10 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170410_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrecipe',
            name='recipe_name',
            field=models.TextField(max_length=220),
        ),
    ]
