# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-10 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_recipecomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipecomment',
            old_name='recipe_comment',
            new_name='recipe_comments',
        ),
    ]
